version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: challenge_backend
    
    ports:
      - "3000:3000"
    restart: always

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.frontend
  #   ports:
  #     - "80:80"
  #   restart: always
