version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: challenge_backend
    restart: always
    ports:
      - "3000:3000"
    networks:
      - challenge-network

  frontend:
    build:
      context: ./frontend/userJourney
      dockerfile: Dockerfile
    container_name: challenge_frontend
    restart: unless-stopped
    ports:
      - "4000:4000"
    depends_on:
      - backend
    networks:
      - challenge-network
    environment:
      NODE_ENV: production
    volumes:
      - ./frontend/userJourney:/app
      - /app/node_modules

networks:
  challenge-network:
    driver: bridge

